<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities [
<!ELEMENT expression (#PCDATA)>
<!ELEMENT math (#PCDATA | expression | evaluation)*>
<!ELEMENT french (#PCDATA)>
<!ELEMENT entities (#PCDATA | math | french)*>
<!ELEMENT evaluation (#PCDATA)> ]>
<entities>
    <math>
        <expression>20 &#x3C;50</expression>
        <evaluation>true;</evaluation>
    </math>
    <french>Il nous t&#xE9;ait tr&#xE8;s agra&#xE9;ble d&apos;prendre que vous avez les numismatiques, mais il nous fachait bien de en m&#xEA;me temps, que vous n&apos; en possedez pas une p&#xE9;reuve.</french>
</entities>
